import json
from pathlib import Path
from datetime import datetime
from zoneinfo import ZoneInfo
P=Path(__file__).parent;x=json.loads((P/'results.json').read_text());a=json.loads((P/'actual-stop-analysis.json').read_text());u=json.loads((P/'uncertainty.json').read_text());scan=json.loads((P/'scan-coverage.json').read_text());pairs=json.loads((P/'paired-trades.json').read_text());raw=json.loads((P/'trades.json').read_text());at=json.loads((P/'collection.json').read_text())['at'];et=lambda t:datetime.fromtimestamp(t,ZoneInfo('America/New_York')).isoformat()
lines=['CRYPTO STOP-PRICE STUDY',f'Snapshot: {et(at)}','Conclusion: Existing logs do not establish an optimal stop. Keep 55 cents pending more evidence; 50 cents is a candidate for prospective comparison, not a validated replacement. No bot settings changed.','', 'Scope: Seven crypto bots; currently visible completed UI trades, excluding cleared history. 2,281 collected; comparisons of the current no-take-profit regime use 2,225 trades entered after September 24, 2026 at 8pm ET, excluding take-profit exits. Stops are held-side bid prices, not loss amounts.','', 'ACTUAL EXECUTION EVIDENCE','Asset | completed trades | hard stops | later winning settlement | actual net P&L | hypothetical hold-to-settlement P&L change']
for asset,v in a.items():lines.append(f"{asset} | {v['trades']} | {v['stops']} | {v['stops_recover_to_win']} | ${v['actual']:.4f} | ${v['no_stop_delta']:+.4f}")
lines+=['','Holding to settlement fixes the original actual entries and sizes, removes actual sells, retains actual purchase fees, and uses recorded official outcomes. It is not a full alternative portfolio simulation: longer exposure can change later orders, loss-guard behavior, and available cash. No-stop delta is not the benefit of any particular lower stop.',f"Actual hard-stop average fill: {a['ALL']['stop_mean_fill']*100:.2f} cents; median 53 cents. {a['ALL']['stop_below50']} filled below 50 cents; {a['ALL']['stop_below40']} below 40 cents.",'','MODELED STOP COMPARISON',f"Common cohort: {x['covered_trades']} trades ({100*x['covered_trades']/a['ALL']['trades']:.1f}% of eligible history), {x['period_et'][0]} through {x['period_et'][1]}. Actual sample P&L ${x['actual_pnl']:.4f}. {sum(not r['settlement_winner'] for r in pairs)} ultimately losing settlement outcomes.",'Stop cents | modeled P&L | delta vs modeled 55c | modeled losing trades | actual winners turned to modeled losses']
for r in x['all']['1.0']:lines.append(f"{r['stop']} | ${r['net_pnl']:.4f} | ${r['delta_vs_modeled55']:+.4f} | {r['losses']} | {r['actual_winners_turned_losses']}")
lines+=['','METHOD','Same original buy quantity, purchase cost and fees for every candidate. First observed fresh valid held-side bid at/below threshold triggers an irrevocable hypothetical exit; first retained book after delay supplies bid depth, not the trigger price. Entire quantity must fit retained depth. Otherwise comparison is unavailable. Trades without a stop use recorded official settlement. No partial-fill or market-impact simulation.','Central delay 1 second; sensitivity 0.5 and 3 seconds. Actual hard-stop detection-to-acknowledgement timing on 295 recorded sells: median 0.54s, p90 2.48s, p95 3.23s. This excludes quote age and earlier unobserved crossings.','Common cohort requires all stops 40–70 cents and all tested delays to have adequate coverage from entry acknowledgement through hypothetical exit (or settlement if no exit), no valid-book gap over 5s, and next execution book within 2s of eligibility. Empty held-side books count as observed but cannot fill an exit. A stricter 2s coverage comparison is retained in results.json. Broader 5–80c scenarios were evaluated on this same cohort.','Recorded book samples may miss intervening crossings. Actual polling, queue delay, liquidity competition, fill confirmation, partial sales and order effects cannot be reconstructed exactly. Actual buy entry acknowledgement is used as exposure start; fills may precede it slightly.','Modeled sell fees use the repository FeeAccumulator at 0.07 and $0.0001 balance precision. Reference: https://kalshi.com/docs/kalshi-fee-schedule.pdf (general taker formula and no settlement fee). Actual buy fees are taken from exchange order records.','', 'VALIDATION AND UNCERTAINTY',f"Modeled 55c central P&L ${next(r['net_pnl'] for r in x['all']['1.0'] if r['stop']==55):.4f}, actual ${x['actual_pnl']:.4f}; mean absolute discrepancy {x['baseline_validation']['mean_absolute_per_contract_cents']:.3f} cents per contract. Modeled deltas must not be added to actual account P&L as guaranteed gains."]
for sample,rr in x['holdout'].items():
 r=next(r for r in rr if r['stop']==50);lines.append(f"50c versus 55c, {sample}: {r['trades']} trades, delta ${r['delta_vs_modeled55']:+.4f}.")
lines+= [f"50c delta across delays: "+', '.join(f"{d}s ${next(v['delta_vs_modeled55'] for v in rr if v['stop']==50):+.4f}" for d,rr in x['all'].items()),f"50c cluster bootstrap 95% delta interval: ${u['50']['bootstrap95_delta_interval'][0]:.2f} to ${u['50']['bootstrap95_delta_interval'][1]:.2f}. 5,000 resamples of {u['50']['cluster_count']} shared 15-minute buckets; exploratory, not adjusted for searching multiple thresholds or model uncertainty.",'Very loose 5c had the highest in-sample modeled P&L, but mean loss per losing contract was 84.70c versus 34.38c at 55c. Its bootstrap interval also spans losses; it is not an acceptable claim of a validated optimum.','The later 30% is a chronological retrospective check, not untouched prospective data. Settings and quantities changed during the history. Per-asset sample sizes are too small for reliable individual optima.','', 'PER-ASSET CENTRAL 40–70c EXPLORATORY COMPARISON','Asset | usable sample | best among 40–70c | modeled delta vs 55c']
for asset,rr in x['by_asset'].items():
 ss=[v for v in rr if 40<=v['stop']<=70];best=max(ss,key=lambda v:v['net_pnl']);lines.append(f"{asset} | {best['trades']} | {best['stop']} | ${best['delta_vs_modeled55']:+.4f}" + (' (all tied; no informative stops)' if max(v['net_pnl'] for v in ss)==min(v['net_pnl'] for v in ss) else ''))
lines+=['','COVERAGE',str(x['excluded']),f"Scanned {sum(v['files'] for v in scan)} compressed collector segments. Read errors: {sum(len(v['errors']) for v in scan)}.",'Final decision: do not raise or lower the live stop on these results alone. Compare 50c and 55c prospectively, particularly on XRP; retain full bid-depth paths for stopped trades and eventual winners.']
(P/'report.txt').write_text('\n'.join(lines)+'\n');print(P/'report.txt')
